In [1]:
a = 10

In [2]:
height = 175

In [3]:
name = "John"

In [4]:
height1 = 153
height2 = 163

In [5]:
if (height1 > height2):
    print("person 1 is taller")
else:
    print("person 2 is taller")

person 2 is taller

In [6]:
def add(a,b):
    print(a+b)

In [7]:
add(10,10)

20

In [9]:
l =[10,20,30,40,'abc',3.5]

In [11]:
l[0] = "apple"

In [12]:
l

['apple', 20, 30, 40, 'abc', 3.5]

In [13]:
d = {1:"apple",2:"mango",3:"orange"}

In [14]:
d[1]

'apple'

In [15]:
person ={"name":"John","age":20,"height":172}

In [17]:
person["age"]

20

In [18]:
import numpy as np

In [19]:
l = [1,2,3,4,5,6]

In [22]:
arr = np.array(l)

In [23]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
import pandas as pd

In [4]:
s = pd. Series ([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
s.dtype

dtype('int64')

In [7]:
s.values

array([10, 20, 30, 40, 50])

In [8]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [9]:
s.name

In [10]:
s.name = "number"

In [11]:
s

0    10
1    20
2    30
3    40
4    50
Name: number, dtype: int64

In [12]:
s[0]

np.int64(10)

In [14]:
s[0:2]

0    10
1    20
Name: number, dtype: int64

In [15]:
s[2:4]

2    30
3    40
Name: number, dtype: int64

In [16]:
s.loc[[1,2,3]]

1    20
2    30
3    40
Name: number, dtype: int64

In [17]:
print(s.name)

number

In [19]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]

In [22]:
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: number, dtype: int64

In [23]:
s["grapes"]

np.int64(30)

In [26]:
s.loc["grapes"]

np.int64(30)

In [27]:
s['banana': 'orange']

banana    20
grapes    30
orange    40
Name: number, dtype: int64

In [31]:
import pandas as pd

s2 = pd.Series([0, 1, 2, 3, 4])

In [32]:
s2[s2 > 1]

2    2
3    3
4    4
dtype: int64

In [33]:
[(s2>0.5) & (s2 < 2)]

[0    False
 1     True
 2    False
 3    False
 4    False
 dtype: bool]

In [35]:
s2[(s2>0.5)|(52 <= 2)]

1    1
2    2
3    3
4    4
dtype: int64

In [37]:
s2[~(s2>1)]

0    0
1    1
dtype: int64

In [38]:
s2["Mango"]= 2.8
s2

0        0.0
1        1.0
2        2.0
3        3.0
4        4.0
Mango    2.8
dtype: float64

In [39]:
import numpy as np

In [41]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
s.notnull().sum()

np.int64(5)

In [42]:
data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"], "Age": [25, 30, 35, np.nan, 29, 25],
"Department": ["HR", "IT", "Finance", "IT", "HR", "HR"], "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [43]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [44]:
df.head(20)

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [46]:
df.tail()

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [48]:
df.tail(3)

    Name   Age Department   Salary
3  David   NaN         IT  62000.0
4    Eve  29.0         HR      NaN
5  Alice  25.0         HR  50000.0

In [49]:
df.iloc[1:3]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [50]:
df.loc[1:3, ["Age", "Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [51]:
df[["Age", "Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [53]:
df.drop("Age", axis = 1 )

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [54]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [55]:
df.drop("Age", axis = 1 ,inplace=True)

In [56]:
df

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [57]:
df.shape

(6, 3)

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Salary      5 non-null      float64
dtypes: float64(1), str(2)
memory usage: 276.0 bytes

In [59]:
df.describe()

             Salary
count      5.000000
mean   58400.000000
std     8532.291603
min    50000.000000
25%    50000.000000
50%    60000.000000
75%    62000.000000
max    70000.000000

In [60]:
df["Salary"]= df["Salary"] + 5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [61]:
df.rename(columns = {"Department": "Dept"}, inplace = True)
df

      Name     Dept   Salary
0    Alice       HR  55000.0
1      Bob       IT  65000.0
2  Charlie  Finance  75000.0
3    David       IT  67000.0
4      Eve       HR      NaN
5    Alice       HR  55000.0

In [62]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [63]:
df["Dept"].unique()

<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str

In [65]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [66]:
df["Promoted Salary"] = df["Salary"] * 10
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  55000.0         550000.0

In [67]:
df.isnull().sum()

Name               0
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [68]:
df.dropna()

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
5    Alice       HR  55000.0         550000.0

In [69]:
df.dropna (how = "any")

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
5    Alice       HR  55000.0         550000.0

In [70]:
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR      NaN              NaN
5    Alice       HR  55000.0         550000.0

In [71]:
df.fillna(0)

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR      0.0              0.0
5    Alice       HR  55000.0         550000.0

In [73]:
print(df.columns)

Index(['Name', 'Dept', 'Salary', 'Promoted Salary'], dtype='str')

In [74]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [75]:
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR  63400.0              NaN
5    Alice       HR  55000.0         550000.0

In [77]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    63400.0
5    55000.0
Name: Salary, dtype: float64

In [82]:
df["Salary"] = df["Salary"].ffill()

In [83]:
df["Name"].replace("Charlie", "Rose")

0    Alice
1      Bob
2     Rose
3    David
4      Eve
5    Alice
Name: Name, dtype: str

In [84]:
df

      Name     Dept   Salary  Promoted Salary
0    Alice       HR  55000.0         550000.0
1      Bob       IT  65000.0         650000.0
2  Charlie  Finance  75000.0         750000.0
3    David       IT  67000.0         670000.0
4      Eve       HR  63400.0              NaN
5    Alice       HR  55000.0         550000.0

In [86]:
department_info= {
"Department": ["HR","IT", "Finance"],
"Location": ["New York", "SanFrancisco","Chicago"],
"Manager":["Laura","Steve","Nina"]
}

In [87]:
df2 = pd.DataFrame (department_info)
df2

  Department      Location Manager
0         HR      New York   Laura
1         IT  SanFrancisco   Steve
2    Finance       Chicago    Nina

In [89]:
pd.concat([df, df2])

      Name     Dept   Salary  Promoted Salary Department      Location Manager
0    Alice       HR  55000.0         550000.0        NaN           NaN     NaN
1      Bob       IT  65000.0         650000.0        NaN           NaN     NaN
2  Charlie  Finance  75000.0         750000.0        NaN           NaN     NaN
3    David       IT  67000.0         670000.0        NaN           NaN     NaN
4      Eve       HR  63400.0              NaN        NaN           NaN     NaN
5    Alice       HR  55000.0         550000.0        NaN           NaN     NaN
0      NaN      NaN      NaN              NaN         HR      New York   Laura
1      NaN      NaN      NaN              NaN         IT  SanFrancisco   Steve
2      NaN      NaN      NaN              NaN    Finance       Chicago    Nina

In [91]:
pd.concat([df, df2], axis=1)

      Name     Dept   Salary  Promoted Salary Department      Location Manager
0    Alice       HR  55000.0         550000.0         HR      New York   Laura
1      Bob       IT  65000.0         650000.0         IT  SanFrancisco   Steve
2  Charlie  Finance  75000.0         750000.0    Finance       Chicago    Nina
3    David       IT  67000.0         670000.0        NaN           NaN     NaN
4      Eve       HR  63400.0              NaN        NaN           NaN     NaN
5    Alice       HR  55000.0         550000.0        NaN           NaN     NaN

In [95]:
print(df.columns)
print(df2.columns)

Index(['Name', 'Dept', 'Salary', 'Promoted Salary'], dtype='str')
Index(['Department', 'Location', 'Manager'], dtype='str')

In [97]:
merged_df = pd.merge(df,df2,left_on="Dept",right_on="Department")
merged_df

      Name     Dept   Salary  Promoted Salary Department      Location Manager
0    Alice       HR  55000.0         550000.0         HR      New York   Laura
1      Bob       IT  65000.0         650000.0         IT  SanFrancisco   Steve
2  Charlie  Finance  75000.0         750000.0    Finance       Chicago    Nina
3    David       IT  67000.0         670000.0         IT  SanFrancisco   Steve
4      Eve       HR  63400.0              NaN         HR      New York   Laura
5    Alice       HR  55000.0         550000.0         HR      New York   Laura

In [98]:
data = pd.read_csv("iris.csv")

In [99]:
data

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [100]:
data.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [101]:
data.shape

(149, 5)

In [102]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    str
dtypes: float64(4), str(1)
memory usage: 5.9 KB

In [106]:
import pandas as pd
columns = ["sepal_length","sepal_width","petal_length","petal_width","species"]
df = pd.read_csv("iris.csv", names=columns)
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [110]:
import pandas as pd

columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

data = pd.read_csv(
    "iris.csv",
    names=columns
)

data.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [111]:
X = data.drop("species", axis=1)

In [112]:
y = data["species"]

In [114]:
from sklearn.ensemble import RandomForestClassifier

In [115]:
model = RandomForestClassifier(n_estimators=100)

In [116]:
model = RandomForestClassifier( n_estimators=1000,random_state=42)

In [118]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [119]:
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1000, random_state=42)

In [120]:
print(X.head())

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [121]:
print(y.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: str

In [122]:
y_pred = model.predict(X_test)

In [123]:
from sklearn.metrics import accuracy_score

In [124]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [125]:
importance = pd.DataFrame({"Feature": X.columns,"Importance": model.feature_importances_})

In [126]:
importance.sort_values(by="Importance",ascending=False)

        Feature  Importance
2  petal_length    0.439375
3   petal_width    0.423570
0  sepal_length    0.105497
1   sepal_width    0.031558

In [127]:
from sklearn.svm import SVC

In [128]:
svm_model = SVC(kernel="rbf",probability=True)

In [129]:
svm_model.fit(X_train, y_train)

c:\Users\DELL\AI_ml-Projects\.venv\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

SVC(probability=True)