# # Day 4 — Pandas: Tabular Data

4.2  Loading and Inspecting Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("iris.csv")

In [26]:
import pandas as pd

columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

df = pd.read_csv("iris.csv", names=columns)

df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [7]:
df.shape

(149, 5)

In [4]:
df.head(20)

    5.1  3.5  1.4  0.2  Iris-setosa
0   4.9  3.0  1.4  0.2  Iris-setosa
1   4.7  3.2  1.3  0.2  Iris-setosa
2   4.6  3.1  1.5  0.2  Iris-setosa
3   5.0  3.6  1.4  0.2  Iris-setosa
4   5.4  3.9  1.7  0.4  Iris-setosa
5   4.6  3.4  1.4  0.3  Iris-setosa
6   5.0  3.4  1.5  0.2  Iris-setosa
7   4.4  2.9  1.4  0.2  Iris-setosa
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa
13  5.8  4.0  1.2  0.2  Iris-setosa
14  5.7  4.4  1.5  0.4  Iris-setosa
15  5.4  3.9  1.3  0.4  Iris-setosa
16  5.1  3.5  1.4  0.3  Iris-setosa
17  5.7  3.8  1.7  0.3  Iris-setosa
18  5.1  3.8  1.5  0.3  Iris-setosa
19  5.4  3.4  1.7  0.2  Iris-setosa

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    str
dtypes: float64(4), str(1)
memory usage: 5.9 KB

In [9]:
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [10]:
df.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [11]:
df.tail(60)

     5.1  3.5  1.4  0.2      Iris-setosa
89   5.5  2.6  4.4  1.2  Iris-versicolor
90   6.1  3.0  4.6  1.4  Iris-versicolor
91   5.8  2.6  4.0  1.2  Iris-versicolor
92   5.0  2.3  3.3  1.0  Iris-versicolor
93   5.6  2.7  4.2  1.3  Iris-versicolor
94   5.7  3.0  4.2  1.2  Iris-versicolor
95   5.7  2.9  4.2  1.3  Iris-versicolor
96   6.2  2.9  4.3  1.3  Iris-versicolor
97   5.1  2.5  3.0  1.1  Iris-versicolor
98   5.7  2.8  4.1  1.3  Iris-versicolor
99   6.3  3.3  6.0  2.5   Iris-virginica
100  5.8  2.7  5.1  1.9   Iris-virginica
101  7.1  3.0  5.9  2.1   Iris-virginica
102  6.3  2.9  5.6  1.8   Iris-virginica
103  6.5  3.0  5.8  2.2   Iris-virginica
104  7.6  3.0  6.6  2.1   Iris-virginica
105  4.9  2.5  4.5  1.7   Iris-virginica
106  7.3  2.9  6.3  1.8   Iris-virginica
107  6.7  2.5  5.8  1.8   Iris-virginica
108  7.2  3.6  6.1  2.5   Iris-virginica
109  6.5  3.2  5.1  2.0   Iris-virginica
110  6.4  2.7  5.3  1.9   Iris-virginica
111  6.8  3.0  5.5  2.1   Iris-virginica
112  5.7  2.5  5.0  2.0   Iris-virginica
113  5.8  2.8  5.1  2.4   Iris-virginica
114  6.4  3.2  5.3  2.3   Iris-virginica
115  6.5  3.0  5.5  1.8   Iris-virginica
116  7.7  3.8  6.7  2.2   Iris-virginica
117  7.7  2.6  6.9  2.3   Iris-virginica
118  6.0  2.2  5.0  1.5   Iris-virginica
119  6.9  3.2  5.7  2.3   Iris-virginica
120  5.6  2.8  4.9  2.0   Iris-virginica
121  7.7  2.8  6.7  2.0   Iris-virginica
122  6.3  2.7  4.9  1.8   Iris-virginica
123  6.7  3.3  5.7  2.1   Iris-virginica
124  7.2  3.2  6.0  1.8   Iris-virginica
125  6.2  2.8  4.8  1.8   Iris-virginica
126  6.1  3.0  4.9  1.8   Iris-virginica
127  6.4  2.8  5.6  2.1   Iris-virginica
128  7.2  3.0  5.8  1.6   Iris-virginica
129  7.4  2.8  6.1  1.9   Iris-virginica
130  7.9  3.8  6.4  2.0   Iris-virginica
131  6.4  2.8  5.6  2.2   Iris-virginica
132  6.3  2.8  5.1  1.5   Iris-virginica
133  6.1  2.6  5.6  1.4   Iris-virginica
134  7.7  3.0  6.1  2.3   Iris-virginica
135  6.3  3.4  5.6  2.4   Iris-virginica
136  6.4  3.1  5.5  1.8   Iris-virginica
137  6.0  3.0  4.8  1.8   Iris-virginica
138  6.9  3.1  5.4  2.1   Iris-virginica
139  6.7  3.1  5.6  2.4   Iris-virginica
140  6.9  3.1  5.1  2.3   Iris-virginica
141  5.8  2.7  5.1  1.9   Iris-virginica
142  6.8  3.2  5.9  2.3   Iris-virginica
143  6.7  3.3  5.7  2.5   Iris-virginica
144  6.7  3.0  5.2  2.3   Iris-virginica
145  6.3  2.5  5.0  1.9   Iris-virginica
146  6.5  3.0  5.2  2.0   Iris-virginica
147  6.2  3.4  5.4  2.3   Iris-virginica
148  5.9  3.0  5.1  1.8   Iris-virginica

In [12]:
df.sample()

    5.1  3.5  1.4  0.2      Iris-setosa
85  6.7  3.1  4.7  1.5  Iris-versicolor

In [13]:
df.sample(5)

     5.1  3.5  1.4  0.2      Iris-setosa
96   6.2  2.9  4.3  1.3  Iris-versicolor
32   5.5  4.2  1.4  0.2      Iris-setosa
29   4.8  3.1  1.6  0.2      Iris-setosa
137  6.0  3.0  4.8  1.8   Iris-virginica
55   6.3  3.3  4.7  1.6  Iris-versicolor

In [14]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='str')

In [18]:
df.dtypes

5.1            float64
3.5            float64
1.4            float64
0.2            float64
Iris-setosa        str
dtype: object

In [19]:
df.isnull()

       5.1    3.5    1.4    0.2  Iris-setosa
0    False  False  False  False        False
1    False  False  False  False        False
2    False  False  False  False        False
3    False  False  False  False        False
4    False  False  False  False        False
..     ...    ...    ...    ...          ...
144  False  False  False  False        False
145  False  False  False  False        False
146  False  False  False  False        False
147  False  False  False  False        False
148  False  False  False  False        False

[149 rows x 5 columns]

In [20]:
df.isnull().sum

<bound method DataFrame.sum of        5.1    3.5    1.4    0.2  Iris-setosa
0    False  False  False  False        False
1    False  False  False  False        False
2    False  False  False  False        False
3    False  False  False  False        False
4    False  False  False  False        False
..     ...    ...    ...    ...          ...
144  False  False  False  False        False
145  False  False  False  False        False
146  False  False  False  False        False
147  False  False  False  False        False
148  False  False  False  False        False

[149 rows x 5 columns]>

In [21]:
df.isnull().sub

<bound method DataFrame.sub of        5.1    3.5    1.4    0.2  Iris-setosa
0    False  False  False  False        False
1    False  False  False  False        False
2    False  False  False  False        False
3    False  False  False  False        False
4    False  False  False  False        False
..     ...    ...    ...    ...          ...
144  False  False  False  False        False
145  False  False  False  False        False
146  False  False  False  False        False
147  False  False  False  False        False
148  False  False  False  False        False

[149 rows x 5 columns]>

In [22]:
df.add_prefix

<bound method NDFrame.add_prefix of      5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]>

In [24]:
df.sort_values

<bound method DataFrame.sort_values of      5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]>

In [25]:
df.add_suffix

<bound method NDFrame.add_suffix of      5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]>

4.3  Selecting and Filtering

In [27]:
df["sepal_length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [28]:
df["petal_width"]

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64

In [29]:
df["petal_length"]

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [30]:
df["species"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: str

In [33]:
df[["sepal_length", "petal_length"]]

     sepal_length  petal_length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [34]:
df[["petal_width", "petal_length"]]

     petal_width  petal_length
0            0.2           1.4
1            0.2           1.4
2            0.2           1.3
3            0.2           1.5
4            0.2           1.4
..           ...           ...
145          2.3           5.2
146          1.9           5.0
147          2.0           5.2
148          2.3           5.4
149          1.8           5.1

[150 rows x 2 columns]

In [35]:
df[df["sepal_length"] > 10]

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

In [36]:
df[df["petal_length"] < 1.4]

    sepal_length  sepal_width  petal_length  petal_width      species
2            4.7          3.2           1.3          0.2  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa
22           4.6          3.6           1.0          0.2  Iris-setosa
35           5.0          3.2           1.2          0.2  Iris-setosa
36           5.5          3.5           1.3          0.2  Iris-setosa
38           4.4          3.0           1.3          0.2  Iris-setosa
40           5.0          3.5           1.3          0.3  Iris-setosa
41           4.5          2.3           1.3          0.3  Iris-setosa
42           4.4          3.2           1.3          0.2  Iris-setosa

In [37]:
df.loc[df["sepal_length"] > 10, "species"]

Series([], Name: species, dtype: str)

In [38]:
df.loc[df["petal_length"] > 1.2, "petal_width"]

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 146, dtype: float64

4.4  Cleaning Data

In [39]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [40]:
df["sepal_length"].fillna(df["sepal_length"].mean(), inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_8988\568224741.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["sepal_length"].fillna(df["sepal_length"].mean(), inplace=True)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [41]:
df["sepal_length"].fillna(df["sepal_length"].mean(), inplace=False)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [42]:
df["petal_width"].fillna(df["petal_width"].mean(), inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_8988\1968091977.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["petal_width"].fillna(df["petal_width"].mean(), inplace=True)

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64

In [43]:
df["petal_width"].fillna(df["petal_width"].mean(), inplace=False)

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64

In [44]:

df.dropna(inplace=True)

In [45]:
df.dropna(inplace=False)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [46]:
df.drop_duplicates(inplace=True)

In [47]:
df.drop_duplicates(inplace=False)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[147 rows x 5 columns]

4.5  Grouping and Aggregation

In [49]:
df.groupby("species")["petal_length"].mean()

species
Iris-setosa        1.462500
Iris-versicolor    4.260000
Iris-virginica     5.561224
Name: petal_length, dtype: float64

In [51]:
df.groupby("petal_width")["petal_length"].mean()

petal_width
0.1    1.375000
0.2    1.442857
0.3    1.428571
0.4    1.571429
0.5    1.700000
0.6    1.600000
1.0    3.628571
1.1    3.566667
1.2    4.240000
1.3    4.176923
1.4    4.637500
1.5    4.658333
1.6    5.025000
1.7    4.750000
1.8    5.333333
1.9    5.375000
2.0    5.550000
2.1    5.783333
2.2    6.033333
2.3    5.700000
2.4    5.433333
2.5    5.933333
Name: petal_length, dtype: float64

In [52]:
df.groupby("petal_width")["petal_length"].max()

petal_width
0.1    1.5
0.2    1.9
0.3    1.7
0.4    1.9
0.5    1.7
0.6    1.6
1.0    4.1
1.1    3.9
1.2    4.7
1.3    4.6
1.4    5.6
1.5    5.1
1.6    5.8
1.7    5.0
1.8    6.3
1.9    6.1
2.0    6.7
2.1    6.6
2.2    6.7
2.3    6.9
2.4    5.6
2.5    6.1
Name: petal_length, dtype: float64

In [53]:
df.groupby("petal_width")["petal_length"].min()

petal_width
0.1    1.1
0.2    1.0
0.3    1.3
0.4    1.3
0.5    1.7
0.6    1.6
1.0    3.3
1.1    3.0
1.2    3.9
1.3    3.6
1.4    3.9
1.5    4.2
1.6    4.5
1.7    4.5
1.8    4.8
1.9    5.0
2.0    4.9
2.1    5.4
2.2    5.6
2.3    5.1
2.4    5.1
2.5    5.7
Name: petal_length, dtype: float64

In [54]:
df.groupby("species").agg({ "sepal_length": "mean","petal_length": "max"})

                 sepal_length  petal_length
species
Iris-setosa          5.010417           1.9
Iris-versicolor      5.936000           5.1
Iris-virginica       6.604082           6.9

In [55]:
df.groupby("species").agg({ "petal_width": "mean","petal_length": "max"})

                 petal_width  petal_length
species
Iris-setosa         0.250000           1.9
Iris-versicolor     1.326000           5.1
Iris-virginica      2.028571           6.9

In [56]:
df.groupby("species").agg({ "petal_width": "min","petal_length": "max"})

                 petal_width  petal_length
species
Iris-setosa              0.1           1.9
Iris-versicolor          1.0           5.1
Iris-virginica           1.4           6.9

In [57]:
df.agg({ "petal_width": "min","petal_length": "max"})

petal_width     0.1
petal_length    6.9
dtype: float64

# # Hands-On Lab: Exploring a Real Dataset with Pandas

Other data was used

 Step 1: Load a provided CSV dataset into a DataFrame and report its shape, columns, and dtypes

In [61]:
import pandas as pd
df = pd.read_csv("data.csv")

In [62]:
df.head

<bound method NDFrame.head of       process.b1.capacity  process.b2.capacity  process.b3.capacity  \
0                       0                    0                    2
1                       0                    0                    2
2                       0                    0                    2
3                       0                    0                    2
4                       0                    0                    2
...                   ...                  ...                  ...
2038                    2                    3                    2
2039                    2                    3                    2
2040                    2                    3                    2
2041                    2                    3                    2
2042                    2                    3                    2

      process.b4.capacity  property.price  property.product  property.winner  \
0                       1              59                 1                0
1                       1              59                 2                0
2                       1              59                 4                0
3                       1              59                 6                0
4                       1              60                 1                0
...                   ...             ...               ...              ...
2038                    1              90                 5                0
2039                    1              90                 5                1
2040                    1              90                 5                2
2041                    1              90                 5                3
2042                    1              90                 5                4

      verification.result  verification.time
0                   False         163.316667
1                   False         200.860000
2                   False         154.888889
3                   False         108.640000
4                    True          85.466667
...                   ...                ...
2038                 True          82.425000
2039                 True        1316.983333
2040                False        9365.450000
2041                False        8474.025000
2042                 True          82.008333

[2043 rows x 9 columns]>

In [63]:
df.shape

(2043, 9)

In [64]:

df.columns

Index(['process.b1.capacity', 'process.b2.capacity', 'process.b3.capacity',
       'process.b4.capacity', 'property.price', 'property.product',
       'property.winner', 'verification.result', 'verification.time'],
      dtype='str')

In [65]:

df.dtypes

process.b1.capacity      int64
process.b2.capacity      int64
process.b3.capacity      int64
process.b4.capacity      int64
property.price           int64
property.product         int64
property.winner          int64
verification.result       bool
verification.time      float64
dtype: object

# #  Step 2: Count missing values per column and handle them (fill or drop) with a documented justification

In [66]:
df.isnull()

,process.b1.capacity,process.b2.capacity,process.b3.capacity,process.b4.capacity,property.price,property.product,property.winner,verification.result,verification.time
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2038,False,False,False,False,False,False,False,False,False
2039,False,False,False,False,False,False,False,False,False
2040,False,False,False,False,False,False,False,False,False
2041,False,False,False,False,False,False,False,False,False
2042,False,False,False,False,False,False,False,False,False

In [67]:
df.isnull().sum()

process.b1.capacity    0
process.b2.capacity    0
process.b3.capacity    0
process.b4.capacity    0
property.price         0
property.product       0
property.winner        0
verification.result    0
verification.time      0
dtype: int64

# # Step 3: Filter the data to a meaningful subset (e.g. rows above a threshold) and describe what you find.

In [68]:
high_price = df[df["property.price"] > 10]

high_price.head()

,process.b1.capacity,process.b2.capacity,process.b3.capacity,process.b4.capacity,property.price,property.product,property.winner,verification.result,verification.time
0,0,0,2,1,59,1,0,False,163.316667
1,0,0,2,1,59,2,0,False,200.860000
2,0,0,2,1,59,4,0,False,154.888889
3,0,0,2,1,59,6,0,False,108.640000
4,0,0,2,1,60,1,0,True,85.466667

In [69]:
high_price.shape

(2043, 9)

# #Step 4: Use groupby to compute an aggregate statistic per category and interpret the result in a 
Markdown cell.

In [70]:
df.groupby("property.product")["verification.time"].max()

property.product
1    23464.666667
2    44130.520833
3     1764.416667
4     1290.483333
5    10424.472222
6     4739.600000
Name: verification.time, dtype: float64

In [ ]:
df.groupby("property.product").agg({"verification.time": "min","property.price": "min"})

                  verification.time  property.price
property.product
1                         82.000000              59
2                         78.000000              59
3                         80.860000              69
4                         77.916667              59
5                         78.791667              69
6                         78.150000              59

In [72]:
df.groupby("property.product").agg({"verification.time": "max","property.price": "max"})

                  verification.time  property.price
property.product
1                      23464.666667              90
2                      44130.520833              80
3                       1764.416667              80
4                       1290.483333              70
5                      10424.472222              90
6                       4739.600000              80