In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [3]:

os.chdir(r"C:\Users\DELL\AI_ml-Projects")
%matplotlib inline

In [ ]:
import os
print(os.getcwd())

C:\Users\DELL\AI_ml-Projects

In [ ]:
import os
print(os.listdir())

['.git', '.gitignore', '.ipynb_checkpoints', '.venv', 'requirements.txt', 'Week-01', 'Week-02', 'Week-03', 'Week-04']

In [11]:
import os
for root, dirs, files in os.walk(r"C:\Users\DELL\AI_ml-Projects"):
    if "iris.csv" in files:
        print(os.path.join(root, "iris.csv"))

C:\Users\DELL\AI_ml-Projects\.venv\Lib\site-packages\sklearn\datasets\data\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-01\Day-04-Python-Fundamentals\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-01\Day-05-Data-Visualization\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-02\Day-01\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-02\Day-04\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-02\Day-05\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-03\Day-01\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-03\Day-03\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-03\Day-04\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-04\Day-01\iris.csv
C:\Users\DELL\AI_ml-Projects\Week-04\Day-02\iris.csv

In [12]:
import pandas as pd

In [13]:
dataset = pd.read_csv(
    r"C:\Users\DELL\AI_ml-Projects\Week-04\Day-02\iris.csv",
    header=None
)

In [14]:
dataset.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [6]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    str
dtypes: float64(4), str(1)
memory usage: 5.9 KB

In [15]:
dataset.columns

Index([0, 1, 2, 3, 4], dtype='int64')

In [17]:
dataset.columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

In [18]:
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [19]:
df = dataset.copy()

In [20]:
X = df.iloc[:, :-1]

In [21]:
y = df.iloc[:, -1]

In [22]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [23]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: str

In [24]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [25]:
model = LogisticRegression(max_iter=1000)

In [26]:
scores = cross_val_score(model,X,y,cv=5,scoring="accuracy")

In [27]:
print(scores)
print("Mean:", scores.mean())
print("Std:", scores.std())

[0.96666667 1.         0.93333333 0.96666667 1.        ]
Mean: 0.9733333333333334
Std: 0.02494438257849294

In [29]:
#from sklearn.linear_model import Ridge
#ridge = Ridge(alpha=1)
#ridge.fit(X, y)
#ridge.coef_
# ما بتزبط هون لهاي الداتا

In [32]:
import pandas as pd
from sklearn.linear_model import Ridge

In [34]:

X = pd.DataFrame([1, 2, 3, 4, 5])
y = pd.Series([2, 4, 6, 8, 10])
ridge = Ridge(alpha=1)
ridge.fit(X, y)
X_test = pd.DataFrame([1, 2, 3, 4])
y_pred = ridge.predict(X_test)
y_pred

array([2.36363636, 4.18181818, 6.        , 7.81818182])

In [35]:
from sklearn.model_selection import train_test_split

In [41]:
import pandas as pd
dataset = pd.read_csv(
    r"C:\Users\DELL\AI_ml-Projects\Week-04\Day-02\iris.csv",
    header=None
)
dataset.columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

print(X.shape)
print(y.value_counts())

(150, 4)
species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)

In [45]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)

In [46]:
from sklearn.model_selection import cross_val_score

In [47]:
scores = cross_val_score(model,X_train,y_train,cv=5,scoring="f1_macro")

In [48]:
print("Scores:", scores)
print("Mean:", scores.mean())
print("Std:", scores.std())

Scores: [0.95816993 0.95816993 0.95816993 0.95816993 1.        ]
Mean: 0.9665359477124185
Std: 0.016732026143790834

In [49]:
cv=5

In [50]:
from sklearn.model_selection import StratifiedKFold

In [51]:
skf = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

In [52]:
stratified_scores = cross_val_score(model,X_train,y_train,cv=skf,scoring="f1_macro")